SELECT P.DUPLIC DUPLICATA, P.DTEMISSAO DT_EMISSAO,
 CASE
  WHEN ((NVL(P.DTRECEBIMENTOPREVISTO, P.DTVENC) > P.DTVENC) AND (P.TXPERMPREVISTO > 0)) THEN
    P.DTRECEBIMENTOPREVISTO
  ELSE P.DTVENC 
  END DT_VENCIMENTO,
P.VALOR, P.CODCLI COD_CLIENTE, C.CLIENTE, C.CGCENT AS CPF_CNPJ, C.TELCELENT TELEFONE, P.CODUSUR RCA

FROM PCPREST P, PCCLIENT C, PCUSUARI U, PCSUPERV S
WHERE C.CODCLI = P.CODCLI
AND  P.DTPAG IS NULL
AND P.CODUSUR = U.CODUSUR
AND U.CODSUPERVISOR = S.CODSUPERVISOR

AND P.DTVENC BETWEEN '01/01/2000' AND (sysdate - 7)
AND U.CODSUPERVISOR IN (1,5,6,7,9,10,11,12,13)
AND --Script para retornar apenas registros com permissão rotina 131
EXISTS( SELECT 1
           FROM PCLIB
          WHERE CODTABELA = TO_CHAR(8)
            AND (CODIGOA  = NVL(P.CODCOB, CODIGOA) OR CODIGOA = '9999')
            AND PCLIB.CODIGOA IS NOT NULL)
AND (P.CODCOB IN ( 'BK3','BK4','BK8' ))
ORDER BY P.CODCLI, P.DTVENC
